package console

import (
	"net/http"

	"github.com/go-chi/chi/v5"
)

func (s *Server) routes() {
	router := chi.NewRouter()
	router.Get("/", func(w http.ResponseWriter, r *http.Request) {
		http.Redirect(w, r, "/halls", http.StatusFound)
	})
	router.Get("/halls", s.page("halls"))
	router.Get("/screens", s.page("screens"))
	router.Get("/lights", s.page("lights"))
	router.Get("/guards", s.page("guards"))

	router.Get("/api/health", s.handleHealth)
	router.Get("/api/stats", s.handleStats)
	router.Get("/api/venues", s.handleListVenues)
	router.Post("/api/venues", s.handleCreateVenue)
	router.Get("/api/venues/{id}", s.handleGetVenue)
	router.Get("/api/venues/{id}/zones", s.handleVenueZones)
	router.Post("/api/venues/{id}/zones", s.handleAttachZone)
	router.Post("/api/venues/{id}/rename", s.handleVenueRename)
	router.Post("/api/venues/{id}/ensure", s.handleVenueEnsure)
	router.Get("/api/venues/{id}/validate", s.handleVenueValidate)
	router.Get("/api/venues/names", s.handleVenueNames)
	router.Get("/api/venues/count", s.handleVenueCount)
	router.Get("/api/venues/{id}/halls", s.handleHallsOfVenue)

	router.Get("/api/halls", s.handleListHalls)
	router.Post("/api/halls", s.handleCreateHall)
	router.Get("/api/halls/{id}", s.handleGetHall)
	router.Post("/api/halls/{id}/layout", s.handleLayoutChange)
	router.Post("/api/halls/{id}/booths/{boothID}", s.handleBoothChange)
	router.Post("/api/halls/{id}/rename", s.handleHallRename)
	router.Post("/api/halls/{id}/attach-zone", s.handleHallAttachZone)
	router.Get("/api/halls/{id}/zones", s.handleHallZoneIDs)
	router.Post("/api/halls/{id}/remove-zone", s.handleHallRemoveZone)
	router.Get("/api/halls/{id}/layout-size", s.handleHallLayoutSize)
	router.Post("/api/halls/{id}/booths/{boothID}/move", s.handleHallMoveBooth)
	router.Post("/api/halls/{id}/booths/{boothID}/remove-position", s.handleHallRemoveBoothPosition)
	router.Get("/api/halls/{id}/booths/{boothID}/exists", s.handleHallBoothExists)
	router.Get("/api/halls/{id}/booth-zones", s.handleHallBoothZones)
	router.Get("/api/halls/{id}/zone-count", s.handleHallZoneCount)
	router.Post("/api/halls/{id}/power-on-all", s.handleHallPowerOnAll)
	router.Post("/api/halls/{id}/power-off-all", s.handleHallPowerOffAll)
	router.Get("/api/halls/{id}/hall-load", s.handleHallLoad)
	router.Post("/api/halls/{id}/dim-all", s.handleHallDimAll)
	router.Get("/api/halls/{id}/partitions", s.handleHallPartitions)
	router.Get("/api/halls/{id}/partitions/{partition}/zones", s.handleHallZonesInPartition)
	router.Get("/api/halls/{id}/partition-count", s.handleHallPartitionCount)

	router.Get("/api/zones", s.handleListZones)
	router.Post("/api/zones", s.handleCreateZone)
	router.Get("/api/zones/{id}", s.handleGetZone)
	router.Post("/api/zones/{id}/split", s.handleSplitZone)
	router.Get("/api/zones/{id}/venue", s.handleZoneVenue)
	router.Post("/api/zones/{id}/rename", s.handleZoneRename)
	router.Post("/api/zones/{id}/partition", s.handleZoneSetPartition)
	router.Get("/api/zones/{id}/dim", s.handleZoneDimLevel)
	router.Post("/api/zones/{id}/dim", s.handleZoneDim)
	router.Post("/api/zones/{id}/dim-level", s.handleZoneSetDimLevel)
	router.Delete("/api/zones/{id}/dim", s.handleZoneClearDim)
	router.Get("/api/zones/{id}/gates", s.handleGatesOfZone)
	router.Get("/api/zones/{id}/routes", s.handleRoutesOfZone)

	router.Get("/api/booths", s.handleListBooths)
	router.Post("/api/booths", s.handleCreateBooth)
	router.Get("/api/booths/{id}", s.handleGetBooth)
	router.Post("/api/booths/{id}/power", s.handleBoothPower)
	router.Post("/api/booths/{id}/load", s.handleBoothSetLoad)
	router.Post("/api/booths/{id}/toggle", s.handleBoothToggle)
	router.Get("/api/booths/{id}/exists", s.handleBoothExists)
	router.Get("/api/booths/powered-count", s.handleBoothPoweredCount)
	router.Get("/api/booths/total-load", s.handleBoothTotalLoad)
	router.Get("/api/booths/powered-load", s.handleBoothPoweredLoad)

	router.Get("/api/gates", s.handleListGates)
	router.Post("/api/gates", s.handleCreateGate)
	router.Get("/api/gates/{id}", s.handleGetGate)
	router.Post("/api/gates/{id}/mode", s.handleGateMode)
	router.Get("/api/gates/armed", s.handleGateArmed)
	router.Get("/api/gates/released", s.handleGateReleasedList)
	router.Get("/api/gates/{id}/state", s.handleGateState)
	router.Get("/api/gates/{id}/durable", s.handleGateDurable)
	router.Post("/api/gates/{id}/disarm", s.handleGateDisarm)
	router.Post("/api/gates/by-name", s.handleGateSetModeByName)
	router.Get("/api/gates/{id}/zone", s.handleGateZone)
	router.Get("/api/gates/{id}/journal-exists", s.handleGateJournalExists)

	router.Get("/api/lights/scenes", s.handleListScenes)
	router.Post("/api/lights/scenes", s.handleCreateScene)
	router.Get("/api/lights/effective/{zoneID}", s.handleEffectiveScene)
	router.Post("/api/lights/evacuate", s.handleEvacuate)
	router.Get("/api/lights/evacuation/{hallID}", s.handleEvacuationState)
	router.Get("/api/lights/scene-names", s.handleLightSceneNames)
	router.Get("/api/lights/scene-count", s.handleLightSceneCount)
	router.Post("/api/lights/scheduled", s.handleLightScheduled)
	router.Get("/api/lights/evacuating", s.handleLightEvacuating)
	router.Post("/api/lights/handover-all", s.handleLightHandoverAll)
	router.Get("/api/lights/screen-count", s.handleLightScreenCount)
	router.Get("/api/lights/screens", s.handleLightScreens)

	router.Get("/api/screens", s.handleListScreens)
	router.Post("/api/screens", s.handleCreateScreen)
	router.Get("/api/screens/{id}", s.handleGetScreen)
	router.Get("/api/screens/{id}/current", s.handleScreenCurrent)
	router.Post("/api/screens/{id}/playlist", s.handleScreenPlaylist)
	router.Post("/api/screens/{id}/tick", s.handleScreenTick)
	router.Post("/api/screens/{id}/reset", s.handleScreenReset)
	router.Get("/api/screens/{id}/position", s.handleScreenPosition)
	router.Get("/api/screens/{id}/playlist-size", s.handleScreenPlaylistSize)
	router.Get("/api/screens/{id}/playlist-exists", s.handleScreenPlaylistExists)
	router.Get("/api/screens/{id}/sponsors", s.handleScreenSponsors)
	router.Get("/api/screens/{id}/clips", s.handleScreenClips)
	router.Get("/api/screens/{id}/handover", s.handleScreenHandover)
	router.Post("/api/screens/{id}/clear-handover", s.handleScreenClearHandover)
	router.Get("/api/screens/{id}/reset-at", s.handleScreenResetAt)
	router.Get("/api/screens/handover", s.handleScreensHandover)
	router.Get("/api/screens/reset-count", s.handleScreenResetCount)
	router.Get("/api/screens/ids", s.handleScreenIDs)
	router.Get("/api/screens/names", s.handleScreenNames)

	router.Get("/api/cameras", s.handleListCameras)
	router.Post("/api/cameras", s.handleCreateCamera)
	router.Get("/api/cameras/{id}", s.handleGetCamera)
	router.Post("/api/cameras/{id}/presets", s.handleCameraPreset)
	router.Get("/api/cameras/{id}/presets", s.handleCameraPresets)
	router.Get("/api/cameras/{id}/presets/{boothID}", s.handleCameraPresetSingle)
	router.Get("/api/cameras/{id}/presets/{boothID}/position", s.handleCameraPresetPosition)
	router.Delete("/api/cameras/{id}/presets/{boothID}", s.handleCameraRemovePreset)
	router.Post("/api/cameras/{id}/refresh", s.handleCameraRefresh)
	router.Post("/api/cameras/{id}/daynight", s.handleCameraDayNight)
	router.Get("/api/cameras/{id}/daynight", s.handleCameraDayNightState)
	router.Post("/api/cameras/{id}/daynight-mode", s.handleCameraSetDayNight)
	router.Post("/api/cameras/{id}/patrol", s.handleCameraPatrol)
	router.Get("/api/cameras/{id}/patrol-target", s.handleCameraPatrolTarget)
	router.Post("/api/cameras/{id}/patrol-rounds", s.handleCameraPatrolRounds)
	router.Get("/api/cameras/{id}/patrol-sequence", s.handleCameraPatrolSequence)
	router.Get("/api/cameras/{id}/patrol-booths", s.handleCameraPatrolBooths)
	router.Get("/api/cameras/{id}/preset-count", s.handleCameraPresetCount)
	router.Get("/api/cameras/night", s.handleCameraNight)
	router.Get("/api/cameras/day", s.handleCameraDay)
	router.Get("/api/halls/{id}/cameras", s.handleCamerasOfHall)
	router.Get("/api/cameras/{id}/hall", s.handleCameraHall)
	router.Get("/api/cameras/season", s.handleCameraSeason)
	router.Post("/api/cameras/season", s.handleCameraSetSeason)
	router.Get("/api/cameras/season-exists", s.handleSeasonExists)

	router.Get("/api/guards/routes", s.handleListRoutes)
	router.Post("/api/guards/routes", s.handleCreateRoute)
	router.Get("/api/guards/routes/{id}", s.handleGetRoute)
	router.Post("/api/guards/routes/{id}/rebuild", s.handleRebuildRoute)
	router.Post("/api/guards/routes/{id}/checkin", s.handleCheckIn)
	router.Get("/api/guards/routes/{id}/checked/{boothID}", s.handleCheckedIn)
	router.Get("/api/guards/routes/{id}/progress", s.handleRouteProgress)
	router.Get("/api/guards/routes/{id}/overdue", s.handleRouteOverdue)
	router.Get("/api/guards/routes/{id}/checkpoint-count", s.handleRouteCheckpointCount)
	router.Post("/api/guards/routes/rebuilt", s.handleRouteRebuildNew)
	router.Get("/api/guards/alarm/{zoneID}", s.handleRouteAlarm)

	router.Get("/api/quota/{hallID}", s.handleGetQuota)
	router.Post("/api/quota", s.handleSetQuota)
	router.Get("/api/quota", s.handleListQuotas)
	router.Post("/api/quota/{hallID}/limit", s.handleQuotaLimit)
	router.Post("/api/quota/{hallID}/reset", s.handleQuotaReset)
	router.Get("/api/quota/{hallID}/available", s.handleQuotaAvailable)
	router.Get("/api/quota/{hallID}/can-reserve", s.handleQuotaCanReserve)
	router.Get("/api/quota/{hallID}/usage", s.handleQuotaUsage)
	router.Get("/api/quota/{hallID}/ledger", s.handleQuotaLedger)
	router.Post("/api/quota/{hallID}/ledger", s.handleQuotaAppendLedger)
	router.Get("/api/quota/{hallID}/ledger-size", s.handleQuotaLedgerSize)

	router.Get("/api/audit", s.handleAudit)
	router.Get("/api/audit/all", s.handleAuditAll)
	router.Get("/api/audit/last", s.handleAuditLast)
	router.Get("/api/audit/actions", s.handleAuditActions)
	router.Get("/api/audit/targets", s.handleAuditTargets)
	router.Get("/api/audit/by-action", s.handleAuditByAction)
	router.Get("/api/audit/by-target", s.handleAuditByTarget)
	router.Get("/api/audit/since", s.handleAuditSince)
	router.Get("/api/audit/size", s.handleAuditSize)
	router.Get("/api/audit/count", s.handleAuditCount)
	router.Post("/api/audit", s.handleAuditRecord)
	router.Post("/api/audit/clear", s.handleAuditClear)
	s.router = router
}

func (s *Server) page(name string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		tmpl, ok := s.pages[name]
		if !ok {
			http.Error(w, "page not found", http.StatusNotFound)
			return
		}
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		if err := tmpl.ExecuteTemplate(w, "base", map[string]string{"Active": name}); err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
}

func (s *Server) handleHealth(w http.ResponseWriter, r *http.Request) {
	writeJSON(w, http.StatusOK, map[string]string{"status": "ok"})
}
